### ISSUE TITLE
No source code for 1.7.2a +

### ISSUE THREAD

**Issue by vn971** [watabou/pixel-dungeon#38]
There is no source code available for 1.7.2a+

It's more honest to stick with open development for a project that says it's "open source".

The lack of sources could attract to forks instead of the original author/project. Also, the lack of sources would probably push f-droid maintainers to mark the project as "deprecated".

**Comment by 00-Evan** [comment]
Watabou has commented that he is currently extremely busy and hasn't been able to release the latest source as a result.

If you think the delay is unreasonable despite that I'd say that's fair, but I don't believe Watabou is actively intending to abandon this project as open source.

**Comment by vn971** [comment]
@00-Evan that's great news! I will not plan any hasty actions then, and really hoping it would continue to be awesome.)

**Comment by phikal** [comment]
He announced he will update it to 1.7.4 soon: 

>@watawatabou I’m going to publish the source code of this version by the end of the week (skipping 1.7.3 and 1.7.4)

https://twitter.com/watawatabou/status/558214768662953984

**Comment by phikal** [comment]
@phikal I meant 1.7.5

**Comment by np511** [comment]
That's good... Now I just need tog finish incorporating the Shattered and your PD features into Super Pixel Dungeon and then I might upgrade from 1.7.2
@00-Evan great job with shattered, the only problem I have is not being able to find the change log.

**Comment by vn971** [comment]
Personally I'd rather stick with @watabou -s original work, presuming it will be in form of "open development"...

**Comment by akien-mga** [comment]
This was fixed with 8760fd8f4a.

**Comment by vn971** [comment]
I'd be glad to see "open development process" and regular code updates in the future. At least it's more attractive to developers that way.

But the ticked as it's currently described can be closed. Thanks!
