### ISSUE TITLE
No Killing Badge on lv21

### ISSUE THREAD

**Issue by mbbush** [watabou/pixel-dungeon#40]
There's an off-by-one error on line 296 of com/watabou/pixeldungeon/scenes/GameScene.java that checks for level 22, instead of lv21.

**Comment by 00-Evan** [comment]
Just decided to test this for a sec on my fork.

This is working correct, as the game descends first, then attempts to validate the badge. so 22 is correct as we don't want to get the badge when we arrive on floor 22, from floor 21.

The whole logic for checking this is fairly iffy (should really do a check on floor 21 itself, boss levels are checked elsewhere), but it does function correctly.
