### ISSUE TITLE
Enabling "Second Quickslot" doesn't persist beyond death

### ISSUE THREAD

**Issue by cmcconomy** [watabou/pixel-dungeon#50]
I'm not sure when it would be advantageous NOT to have a second quickslot, in any case it would be nice if we didn't have to re-enable it after each death.

**Comment by rodriformiga** [comment]
Solved in 5d366cb5df56c8eff1bf411b5ad9d112ee5dbf93, where the second quickslot option is saved in the Global preferences ;)

**Comment by cmcconomy** [comment]
Thanks!
