### ISSUE TITLE
View Locked Chest Contents

### ISSUE THREAD

**Issue by thegrapesoda** [watabou/pixel-dungeon#55]
Android version.

Spotted an issue on a level that provided me with two locked chests with a single golden key to use on one or the other.  Following the below steps, I was able to see what item type was contained in the locked chests without having to open them.

I left the room with the chests, hiding them from my active view.  I then tapped on the square where I knew one of the chests was.  Player Character walked into the room and shared a space with the chest.  In the upper right of the screen, where it shows what items are on the same square, it showed the item that was in the chest (a staff), rather than the chest itself.  Leaving the room and then navigating to the square where the other chest was allowed me to see that the second chest held a ring (again, without using my key and opening the chest).

If it happens again, I'll be sure to grab a picture.

**Comment by squigish** [comment]
You know that you can see what's in a crystal chest by using the question
mark tool, right? It'll tell you "teak wand" or "ruby ring", unless you've
identified that object before, in which case it'll tell you "wand of
firebolt" or whatever.

**Comment by thegrapesoda** [comment]
Did not know, but thanks.  Is it by design though?

**Comment by squigish** [comment]
It sounds like you're describing a crystal chest, where the idea is that
you can only have one of the two items, and you get a little information
about what they are to use to decide.

I think that being able to stand on the chests is likely a bug, but it
seems pretty minor to me. However, I'm not the one writing the code for
this project.
