### ISSUE TITLE
Save state of second quick slot

### ISSUE THREAD

**Issue by Sebring** [watabou/pixel-dungeon#56]
I'm new to Pixel Dungeon, hence I die a lot. Every time I start over I need to go to `menu` -> `settings` -> `extra quick slot`.

I think it should save the state of the quick slot so this does not need to be done for every run in the dungeon.

[enhancement] [android]

**Comment by anubiann00b** [comment]
:+1: 

I don't think the developer is particularly active here though. There might be a fork you'd have more luck with, like Shattered Pixel Dungeon: https://github.com/00-Evan/shattered-pixel-dungeon

**Comment by rodriformiga** [comment]
I have implemented this in the game, using the same class of global settings.
Changes can be seen in the commit 5d366cb5df56c8eff1bf411b5ad9d112ee5dbf93

**Comment by Sebring** [comment]
Ah ok, I see. 
Thank you both.
