### ISSUE TITLE
Error of incompatible types casting

### ISSUE THREAD

**Issue by uselessscat** [watabou/pixel-dungeon#64]
In the file "RegularLevel.java", near the line 680 there are a line tha says:
room = new HashSet<Room> (( Collection<? extends Room>) bundle.getCollection("rooms"));
But the compiler trows an error of incompatible casting.

**Comment by NotTsunami** [comment]
https://github.com/watabou/pixel-dungeon/pull/41

**Comment by Arie-X** [comment]
Thanks Tsunamical the solution given in #41 is more elegant, jeje.
