### ISSUE TITLE
FloatMath is deprecated since API23

### ISSUE THREAD

**Issue by HellPie** [watabou/pixel-dungeon#65]
Android declared deprecated the FloatMath class in API 23 (Marshmallow/6.0) which is used in this app.
All the code is supposed to be already gone in the current sdks, but it is just marked as deprecated to me.
Since the FloatMath just casts the returns of Math calls to float, it should be an easy fix to avoid future problems and make the game less dependant on custom class implementation for easier multiplatform support.
I will try to request a pull in hopefully less than 2 weeks (My schedule is overcrowded with school tests in this week)

Would you prefer a straight conversion to (float) Math. everywhere when FloatMath is called or a custom FloatMath class only implementing the needed methods and a straight include "reditect" whenever FloatMath is used?

**Comment by NotTsunami** [comment]
(float).math is the easiest solution, as I've done with my fork. Don't bother with a pull request though, watabou never checks/merges anything.

**Comment by HellPie** [comment]
Thank you. I still think that, for complete ess sake, a commit is still worth it. :+1:
