### ISSUE TITLE
Scroll of Wipe Out and Shopkeeper

### ISSUE THREAD

**Issue by andrii-rieznik** [watabou/pixel-dungeon#68]
If scroll of wipe out used outside shop the shopkeeper dies and we can take a free loot. I think it's cheat. If not just close this issue.

pixel-dungeon/src/com/watabou/pixeldungeon/items/scrolls/ScrollOfWipeOut.java:
add `if (!Bestiary.isBoss( mob | mob.name != "shopkeeper")) {`
instead:
`if (!Bestiary.isBoss( mob )) {`
89 line

**Comment by codepants** [comment]
after some time i find this the biggest incentive getting wipeout in the 1st place1
