### ISSUE TITLE
Drinking from the knowledge well has no effect

### ISSUE THREAD

**Issue by gabrielpopa** [watabou/pixel-dungeon#72]
All scrolls from the inventory were still unidentified. Potions also. Nothing new on the weapons or armor which still remained with the question mark on them.

**Comment by pforhan** [comment]
Don't you have to wear things for them to be identified?  Not sure if things in quickCast slots are included either, I think it's only worn rings, weapons, armor.

**Comment by gabrielpopa** [comment]
Yes, you're right. Although it doesn't seem logical that knowledge is limited to worn items. Closing the issue because it's not a bug, but a design decision.
