### ISSUE TITLE
PC source code

### ISSUE THREAD

**Issue by x10102** [watabou/pixel-dungeon#75]
Please upload pixel dungeon source code for PC

**Comment by ahmadalfy** [comment]
what? it exists?

**Comment by markozajc** [comment]
See [here](https://github.com/Arcnor/pixel-dungeon-gdx).

**Comment by Zireael07** [comment]
@markozajc: That fork is 4 years old...

**Comment by pixelherodev** [comment]
I don't think Watabou *has* up-to-date PC source. That fork was the only place it ever existed.

If you want up-to-date PC builds of vanilla PD, clone the fork and merge in the newer commits from here.

**Comment by markozajc** [comment]
2 years later be like
