### ISSUE TITLE
Throwing seed from backpack to alchemy pot breaks 

### ISSUE THREAD

**Issue by funcJeff** [watabou/pixel-dungeon#85]
The alchemy pot seems to work by tapping on it and selecting a seed to throw in it from menu which appears. However, stood next to alchemy pot & opened backpack & selected seed & threw into alchemy pot. My method did not work. The seed and the alchemy pot now merely occupy the same square. 

I cannot pick up the seed because the alchemy pot menu comes up.

**Comment by watabou** [comment]
From [wiki](http://pixeldungeon.wikia.com/wiki/Alchemy):

> As of Update 1.6.4, you can no longer step on a tile with an Alchemy Pot by tapping it; and therefore, you can't pick up an item there in this way. Instead, you need to tap a wall behind the Alchemy Pot.

And you need to throw (this way or another) 3 seeds into the pot to transmute them into a potion. As long as there are not enough of them there nothing happens.
