### ISSUE TITLE
Enhancement: integration with Google Play Game Services

### ISSUE THREAD

**Issue by clemp6r** [watabou/pixel-dungeon#9]
What about integrating Google Play Game Services SDK (to have leaderboards, achivements, etc.) ?

**Comment by Ferk** [comment]
Definitely, some way to compete with friends for score would improve the replayability. Google play already provides the framework, and we already have integration with it for saving the achievements. Just go one step forward.

**Comment by vndmtrx** [comment]
Great addition @watabou! +1

**Comment by anubiann00b** [comment]
Since this is done can we close this issue?

**Comment by vndmtrx** [comment]
I believe so.

**Comment by rraallvv** [comment]
So, was this added to the source code in this repository?
