### ISSUE TITLE
Comments, kinda lacking

### ISSUE THREAD

**Issue by ConnahGriffin** [watabou/pixel-dungeon#95]
Thanks a ton for the code, it will be my college project. But the lack of comments in some places made it hard to navigate for the first few days. But thanks a lot.

**Comment by erwang01** [comment]
Would be happy to see a PR with your comments / improvements!

**Comment by ConnahGriffin** [comment]
@erwang01 I didn't give any comments to what was left off, all I did was give some support for newer android versions(4.4. - 10+, I think this one supports more of the older android versions tho), changed some of the for loops to a switch and vice versa. Made some optimization on the switch cases but they're harder to read now...which is kinda sad. As a whole, no improvements.

I'm using this to learn java, so I'm not as efficient as I want to be.
